name: Publish package to GitHub Packages
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: 12.13.0
          registry-url: https://npm.pkg.github.com/
          # Defaults to the user or organization that owns the workflow file
          scope: "@OntimizeWeb"
          always-auth: true
      - name: install
        run: |
          npm i
      - name: Update package.json names
        run: |
          sed -i '2,2s/ontimize-web-ngx-hello-world/@OntimizeWeb\/ontimize-web-ngx-hello-world/g' package.json
          sed -i '2,2s/ontimize-web-ngx-hello-world/@OntimizeWeb\/ontimize-web-ngx-hello-world/g' projects/ontimize-web-ngx-hello-world/package.json
      - run: echo registry=https://npm.pkg.github.com/OntimizeWeb >> .npmrc
      - name: build
        run: |
          npm run build
      - name: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.OWEB_GH_TOKEN_PUSH }}
        run: |
          npm publish dist/
